name: Venelin Mitov
description: My research and software contributions
url: https://venelin.github.io

permalink: /:categories/:title/
future: true

exclude:
  - "venelin.github.io.Rproj"
  - "data-raw"
  - ".Rproj.user"
  - "vendor"
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"

projects:
  - venelin/SPLITT
  - venelin/PCMBaseCpp
  - venelin/PCMBase
  - venelin/POUMM
  